# Generated by Django 4.1.7 on 2023-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
            ],
        ),
    ]
