# Generated by Django 4.1.7 on 2023-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
