# Generated by Django 4.1.7 on 2023-03-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutUs',
        ),
    ]
