# Generated by Django 4.1.7 on 2023-03-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_about_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metals',
        ),
    ]
